In [142]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [143]:

import pandas as pd

df = pd.read_csv(
    r"C:\Users\shiva\Downloads\messy_customer_sales_data.csv",
    encoding="latin1"
)

df.head(2)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india

In [144]:
df.shape

(10200, 12)

In [145]:
df.dropna().shape

(4528, 12)

In [146]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [147]:
for col in df.columns:
    if df[col].nunique()<20:
        print(df[col].value_counts())
        print('_'*50)

Gender
f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: count, dtype: int64
__________________________________________________
City
Kolkata       820
Mumbai        812
Chennai       784
Bangalore     773
Hyderabad     770
Delhi         763
CHENNAI       404
KOLKATA       395
MUMBAI        393
hyderabad     384
bangalore     383
DELHI         378
delhi         369
BANGALORE     363
HYDERABAD     360
mumbai        352
chennai       343
kolkata       338
Name: count, dtype: int64
__________________________________________________
Feedback_Score
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: count, dtype: int64
__________________________________________________
Country
India    7132
IND       793
india     772
InDia     771
Name: count, dtype: int64
__________________________________________________

In [148]:
df.head(2)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india

In [149]:
df['City'].unique()

array([' KOLKATA ', nan, ' hyderabad ', ' CHENNAI ', ' kolkata ',
       ' BANGALORE ', ' Hyderabad ', ' HYDERABAD ', ' Mumbai ',
       ' chennai ', ' Delhi ', ' bangalore ', ' MUMBAI ', ' Bangalore ',
       ' Kolkata ', ' delhi ', ' Chennai ', ' mumbai ', ' DELHI '],
      dtype=object)

In [150]:
df['City']=df['City'].str.strip().str.lower().replace({'hyderabad':'Hyderbad','mumbai':'MUMBAI','delhi':'Delhi','KOLKATA':'Kolkata ','DELHI':'Delhi'})

# Handle Missing Value

In [151]:
df.isnull().sum()

Customer_ID           1023
Name                     0
Gender                1026
Age                    951
City                  1016
Signup_Date              0
Last_Purchase_Date    1012
Purchase_Amount       1021
Feedback_Score        1023
Email                    0
Phone_Number             0
Country                732
dtype: int64

In [152]:
df.dropna(subset=['Customer_ID'],inplace=True)

In [153]:
df['Age'].unique()

array(['52.0', '51.0 years', '62.0', '40.0', '41.0', nan, '18.0',
       '43.0 years', '40.0 years', '26.0', '32.0', '22.0', '59.0', '65.0',
       '61.0', '31.0', '54.0 years', '55.0', '69.0', '61.0 years', '24.0',
       '63.0', '19.0', '50.0', '56.0', '36.0', '68.0', '43.0', '38.0',
       '27.0', '57.0 years', '23.0', '25.0', '66.0', '28.0', '30.0',
       '46.0', '48.0', '20.0', '37.0', '67.0', '51.0', '35.0', '58.0',
       '29.0', 'nan years', '39.0', '49.0', '47.0', '42.0', '44.0',
       '64.0', '53.0', '60.0', '59.0 years', '45.0', '21.0', '34.0',
       '54.0', '48.0 years', '46.0 years', '33.0', '57.0', '30.0 years',
       '58.0 years', '35.0 years', '34.0 years', '69.0 years', '250',
       '19.0 years', '27.0 years', '53.0 years', '65.0 years',
       '66.0 years', '44.0 years', '49.0 years', '25.0 years',
       '23.0 years', '62.0 years', '41.0 years', '33.0 years',
       '28.0 years', '22.0 years', '20.0 years', '42.0 years',
       '45.0 years', '3', '63.0 years', '37.0 years', '38.0 years',
       '55.0 years', '18.0 years', '36.0 years', '67.0 years',
       '29.0 years', '39.0 years', '31.0 years', '47.0 years',
       '52.0 years', '-10', '60.0 years', '24.0 years', '26.0 years',
       '21.0 years', '64.0 years', '50.0 years', '68.0 years',
       '32.0 years', '56.0 years'], dtype=object)

In [154]:

df['Age'] = df['Age'].replace('nan', pd.NA)

df['Age'] = pd.to_numeric(
    df['Age'].astype(str).str.extract(r'(\d+)')[0],
    errors='coerce'
)

age_median = int(df['Age'].median())

df['Age'] = df['Age'].fillna(age_median)

df['Age'] = df['Age'].astype(int)

In [155]:
df['Age'].unique()

array([ 52,  51,  62,  40,  41,  43,  18,  26,  32,  22,  59,  65,  61,
        31,  54,  55,  69,  24,  63,  19,  50,  56,  36,  68,  38,  27,
        57,  23,  25,  66,  28,  30,  46,  48,  20,  37,  67,  35,  58,
        29,  39,  49,  47,  42,  44,  64,  53,  60,  45,  21,  34,  33,
       250,   3,  10])

In [156]:
df['Purchase_Amount']=df['Purchase_Amount'].fillna(df['Purchase_Amount'].mean())

In [157]:
df['Feedback_Score'].fillna(df['Feedback_Score'].mode()[0],inplace=True)

C:\Users\shiva\AppData\Local\Temp\ipykernel_9276\1359314884.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Feedback_Score'].fillna(df['Feedback_Score'].mode()[0],inplace=True)

In [158]:
df.head(2)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52,kolkata,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india

In [159]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score          0
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [160]:
df['Feedback_Score'].unique()

array([ 1.,  2.,  8., 10.,  3.,  9.,  4.,  7.,  5.,  6.])

In [161]:
for col in ['Gender','City','Country']:
    df[col].fillna(df[col].mode()[0],inplace=True)

C:\Users\shiva\AppData\Local\Temp\ipykernel_9276\126056359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

In [166]:
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    0
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

In [163]:
df.head(2)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52,kolkata,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51,MUMBAI,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india

In [167]:
df['Last_Purchase_Date'] = df['Last_Purchase_Date'].ffill()

In [177]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [176]:
df['Gender']=df['Gender'].str.strip().str.lower().replace({'m':'Male','f':'Female','female':'Female','male':'Male'})

In [184]:
df['City'].unique()

array(['Kolkata', 'Mumbai', 'Hyderbad', 'Chennai', 'Bangalore', 'Delhi'],
      dtype=object)

In [185]:
df['City']=df['City'].str.strip().str.title()

In [191]:
df['Country'].unique()

array(['India'], dtype=object)

In [190]:
df['Country']=df['Country'].str.strip().str.title().replace({'india':'India','InDia':'India','IND':'India','Ind':'India'})

In [197]:
df[df.duplicated].shape

(0, 12)

In [205]:
df.shape

(9000, 12)

In [195]:
df.drop_duplicates(inplace=True)

In [204]:
df['Customer_ID'].value_counts()

Customer_ID
CUST4371    1
CUST8487    1
CUST7407    1
CUST8555    1
CUST6567    1
           ..
CUST9023    1
CUST5769    1
CUST6395    1
CUST4323    1
CUST4812    1
Name: count, Length: 9000, dtype: int64

In [203]:
df.drop_duplicates(subset=['Customer_ID'],keep='first',inplace=True)

In [199]:
df.head(2)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,Male,52,Kolkata,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,Male,51,Mumbai,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,India

# Changed Data Type

In [210]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9000 entries, 0 to 10198
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9000 non-null   object
 1   Name                9000 non-null   object
 2   Gender              9000 non-null   object
 3   Age                 9000 non-null   int64
 4   City                9000 non-null   object
 5   Signup_Date         9000 non-null   datetime64[ns]
 6   Last_Purchase_Date  9000 non-null   datetime64[ns]
 7   Purchase_Amount     9000 non-null   float64
 8   Feedback_Score      9000 non-null   float64
 9   Email               9000 non-null   object
 10  Phone_Number        9000 non-null   int64
 11  Country             9000 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(6)
memory usage: 914.1+ KB

In [208]:
df['Signup_Date']=pd.to_datetime(df['Signup_Date'],errors='coerce')

In [209]:
df['Last_Purchase_Date']=pd.to_datetime(df['Last_Purchase_Date'],errors='coerce')